name=input('Enter the name/')
city=input('Enter the city/')
days=input('Enter the number of days/')
print(f'Hi,I am {name} and I am traveling to {city} for {days} days.') 
name1=input('Enter the name/')
subject=input('Enter the subject/')
marks=input('Enter the marks/')
print('Student {} scored {} marks in {}'.format (name1, marks, subject))
movie=input('Enter the name of the maovie')
year=input('Enter the release year')
rating=input('Enter the ratings')
print('I watched,', movie , 'released in', year, 'and rated it', rating,'\10')
item=input('Enter the item name')
quantity=input('Enter the quantity')
prize=input('Enter the prize')
print(f'You brought {item} x {quantity} for a total of ${prize}')
subject=input('Enter the subject')
date=input('Enter the date')
days=input('Enter the number of days left')
print('Your {} exam is on {} , which is in {} days.'.format(subject,date,days))